export const CHANGE_NAME = 'CHANGE_NAME';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const UPDATE_DATA = 'UPDATE_DATA';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';

export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
